### ISSUE TITLE
USER STORY: Sign in with Username/Password

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/My-First-Agile-Project#6]
As a **user** I can **sign in with a username and password** so that **I can interact with the site more efficiently**

## Acceptance Criteria

* The username should allow numbers and special characters
* The username should be limited to fourteen characters
* The user should have a 'remember me' option
* The password's characters should be hidden unless requested to be seen

## Tasks

- [ ] Create a login option which contains a username that is password protected
- [ ] Limit username options to fourteen characters
- [ ] Create option to hide or reveal user's password
- [ ] Code 'remember me' option
- [ ] Test functionality
