### ISSUE TITLE
USER STORY: One-click shopping

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/My-First-Agile-Project#7]
As a **user** I can **make purchases with one click** so that **my checkout time is greatly reduced**

## Acceptance Criteria

* This should remember the customer's preferred method of payment
* This should remember the customer's shipping info
* Customer should be able to easily add items to a cart and continue shopping
* This should have an icon to show the user's current cart sales total 
* This should send the customer an automatic confirmation email

## Tasks

- [ ] Create button for one-click purchasing
- [ ] Create database for remembering customer's payment method
- [ ] Create database for storing customer's shipping info
- [ ] Create icon to display current sales total for customer
- [ ] Make automatic email confirmation message
- [ ] Test functionality
