### ISSUE TITLE
USER STORY: Add profile image

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/My-First-Agile-Project#8]
As a **customer** I can **add a profile image** so that **my username is personalized**

## Acceptance Criteria

* Customer should be able to change this at any time
* Customer should have the option to store different images, but only display one at a time
* This should only be optional, not mandatory

## Tasks

- [ ] Create section by username to display profile image
- [ ] Create space to store all past profile images if desired
- [ ] Make this an optional feature, not required
- [ ] Test functionality
