### ISSUE TITLE
USER STORY: Reset password

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/My-First-Agile-Project#9]
As a **customer** I can **reset my password** so that **I can keep access to my account secure, or recover my account**

## Acceptance Criteria

* This should require customer to enter old password, or associated email address
* This should send a reset password link to customer's associated email address
* Link should prompt customer to enter new password in twice to confirm

## Tasks

- [ ] Create 'reset password'/'I forgot my password' box at login prompt
- [ ] Create popup that asks customer to enter old password, or associated email address
- [ ] Make email notifier that sends out reset link to customer's associated email address
- [ ] Require customer to enter new password twice to confirm
- [ ] Test functionality
